/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author esmeralda.iyescas001
 */
public class Cookbook extends javax.swing.JFrame {

    /**
     * Creates new form Cookbook
     */
    public Cookbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMeal = new javax.swing.ButtonGroup();
        buttonGroupLifestyle = new javax.swing.ButtonGroup();
        buttonGroupTime = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NextButton1 = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        HungryQ = new javax.swing.JLabel();
        Bfast = new javax.swing.JRadioButton();
        Lunch = new javax.swing.JRadioButton();
        Din = new javax.swing.JRadioButton();
        Snack = new javax.swing.JRadioButton();
        LifestyleQ = new javax.swing.JLabel();
        EatAll = new javax.swing.JRadioButton();
        Veggie = new javax.swing.JRadioButton();
        Vegan = new javax.swing.JRadioButton();
        Pesc = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Gluten = new javax.swing.JCheckBox();
        Dairy = new javax.swing.JCheckBox();
        Egg = new javax.swing.JCheckBox();
        Nuts = new javax.swing.JCheckBox();
        NA = new javax.swing.JCheckBox();
        Dessert = new javax.swing.JRadioButton();
        jButtonGo = new javax.swing.JButton();
        jLabelPic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CookEasy = new javax.swing.JRadioButton();
        CookMed = new javax.swing.JRadioButton();
        CookHard = new javax.swing.JRadioButton();
        ClearButton = new javax.swing.JButton();
        BackButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaINSTRUCT = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaINGRED = new javax.swing.JTextArea();
        Ingredients = new javax.swing.JLabel();
        Instructions = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        StartOver1 = new javax.swing.JButton();
        NameOfDish = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(255, 251, 234));

        jPanel3.setBackground(new java.awt.Color(245, 237, 214));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Welcome to your virtual kitchen :)");

        NextButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        NextButton1.setForeground(new java.awt.Color(153, 51, 0));
        NextButton1.setText("Next >> :p");
        NextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton1ActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Name.setText("Enter your name: ");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/homer_3_99.gif"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel6.setText("Y'all ready to have your taste buds blasted?");

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel8.setText(" If so, click next >> :3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(207, 207, 207)
                        .addComponent(NextButton1)
                        .addGap(75, 75, 75))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel8)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addGap(115, 115, 115)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addGap(51, 51, 51))
        );

        jTabbedPane2.addTab("Welcome", jPanel3);

        jPanel1.setBackground(new java.awt.Color(245, 237, 214));

        Title.setFont(new java.awt.Font("Lucida Sans", 3, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 153, 51));
        Title.setText("Esm's Cookbook");

        HungryQ.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        HungryQ.setForeground(new java.awt.Color(153, 51, 0));
        HungryQ.setText("Which meal?");

        Bfast.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupMeal.add(Bfast);
        Bfast.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Bfast.setForeground(new java.awt.Color(133, 94, 33));
        Bfast.setText("Breakfast");
        Bfast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfastActionPerformed(evt);
            }
        });

        Lunch.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupMeal.add(Lunch);
        Lunch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Lunch.setForeground(new java.awt.Color(133, 94, 33));
        Lunch.setText("Lunch");
        Lunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LunchActionPerformed(evt);
            }
        });

        Din.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupMeal.add(Din);
        Din.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Din.setForeground(new java.awt.Color(133, 94, 33));
        Din.setText("Dinner");

        Snack.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupMeal.add(Snack);
        Snack.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Snack.setForeground(new java.awt.Color(133, 94, 33));
        Snack.setText("Snack");

        LifestyleQ.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        LifestyleQ.setForeground(new java.awt.Color(153, 51, 0));
        LifestyleQ.setText("Which lifestyle?");

        EatAll.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupLifestyle.add(EatAll);
        EatAll.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        EatAll.setForeground(new java.awt.Color(133, 94, 33));
        EatAll.setText("I eat everything!");
        EatAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EatAllActionPerformed(evt);
            }
        });

        Veggie.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupLifestyle.add(Veggie);
        Veggie.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Veggie.setForeground(new java.awt.Color(133, 94, 33));
        Veggie.setText("Vegeterian");

        Vegan.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupLifestyle.add(Vegan);
        Vegan.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Vegan.setForeground(new java.awt.Color(133, 94, 33));
        Vegan.setText("Vegan");

        Pesc.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupLifestyle.add(Pesc);
        Pesc.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Pesc.setForeground(new java.awt.Color(133, 94, 33));
        Pesc.setText("Pescatarian");
        Pesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PescActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Any food restrictions?");

        Gluten.setBackground(new java.awt.Color(240, 231, 211));
        Gluten.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Gluten.setForeground(new java.awt.Color(133, 94, 33));
        Gluten.setText("Gluten");

        Dairy.setBackground(new java.awt.Color(240, 231, 211));
        Dairy.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Dairy.setForeground(new java.awt.Color(133, 94, 33));
        Dairy.setText("Lactose");

        Egg.setBackground(new java.awt.Color(240, 231, 211));
        Egg.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Egg.setForeground(new java.awt.Color(133, 94, 33));
        Egg.setText("Eggs");
        Egg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EggActionPerformed(evt);
            }
        });

        Nuts.setBackground(new java.awt.Color(240, 231, 211));
        Nuts.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Nuts.setForeground(new java.awt.Color(133, 94, 33));
        Nuts.setText("Nuts ");
        Nuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutsActionPerformed(evt);
            }
        });

        NA.setBackground(new java.awt.Color(240, 231, 211));
        NA.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        NA.setForeground(new java.awt.Color(133, 94, 33));
        NA.setText("None");

        Dessert.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupMeal.add(Dessert);
        Dessert.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Dessert.setForeground(new java.awt.Color(133, 94, 33));
        Dessert.setText("Dessert");

        jButtonGo.setBackground(new java.awt.Color(0, 204, 0));
        jButtonGo.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jButtonGo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGo.setText("I'm ready to EAT! :D");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        jLabelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/SimpsonsEating_50.gif"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("Cookin' time");

        CookEasy.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupTime.add(CookEasy);
        CookEasy.setForeground(new java.awt.Color(133, 94, 33));
        CookEasy.setText("Quick-n-easy");

        CookMed.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupTime.add(CookMed);
        CookMed.setForeground(new java.awt.Color(133, 94, 33));
        CookMed.setText("Under 30m");

        CookHard.setBackground(new java.awt.Color(240, 231, 211));
        buttonGroupTime.add(CookHard);
        CookHard.setForeground(new java.awt.Color(133, 94, 33));
        CookHard.setText("Hour+");

        ClearButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ClearButton.setText("Clear :)");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        BackButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        BackButton2.setText("<< Back");
        BackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HungryQ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bfast)
                                    .addComponent(Lunch)
                                    .addComponent(Din)
                                    .addComponent(Snack)
                                    .addComponent(Dessert))))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LifestyleQ, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EatAll)
                                    .addComponent(Pesc)
                                    .addComponent(Veggie)
                                    .addComponent(Vegan))))
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NA)
                                    .addComponent(Gluten)
                                    .addComponent(Dairy)
                                    .addComponent(Egg)
                                    .addComponent(Nuts)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CookEasy)
                                    .addComponent(CookMed)
                                    .addComponent(CookHard)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel4)))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPic)
                        .addGap(140, 140, 140)
                        .addComponent(jButtonGo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Title)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addComponent(CookEasy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CookMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CookHard))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(HungryQ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bfast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lunch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Din)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Snack))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LifestyleQ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(EatAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Veggie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Vegan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dessert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gluten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dairy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Egg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nuts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPic)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BackButton2)
                                .addGap(18, 18, 18)
                                .addComponent(ClearButton))
                            .addComponent(jButtonGo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );

        jTabbedPane2.addTab("Kitchen", jPanel1);

        jPanel2.setBackground(new java.awt.Color(244, 236, 215));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("BON APPETIT  MES AMIES :) ");

        jTextAreaINSTRUCT.setColumns(20);
        jTextAreaINSTRUCT.setRows(5);
        jScrollPane1.setViewportView(jTextAreaINSTRUCT);

        jTextAreaINGRED.setColumns(20);
        jTextAreaINGRED.setRows(5);
        jScrollPane2.setViewportView(jTextAreaINGRED);

        Ingredients.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        Ingredients.setForeground(new java.awt.Color(153, 51, 0));
        Ingredients.setText("Ingredients ");

        Instructions.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        Instructions.setForeground(new java.awt.Color(153, 51, 0));
        Instructions.setText("Instructions");

        BackButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        BackButton.setText("<< BACK ");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        StartOver1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        StartOver1.setText("Start Over");
        StartOver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartOver1MouseClicked(evt);
            }
        });
        StartOver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartOver1ActionPerformed(evt);
            }
        });

        NameOfDish.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        NameOfDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameOfDishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BackButton)
                .addGap(150, 150, 150)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StartOver1)
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(Ingredients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Instructions)
                .addGap(108, 108, 108))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(NameOfDish, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackButton)
                            .addComponent(StartOver1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(NameOfDish, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingredients)
                    .addComponent(Instructions))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18))
        );

        jTabbedPane2.addTab("Table", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        // TODO add your handling code here:
        //if goes here!
        //Breakfast
        if( Bfast.isSelected() && EatAll.isSelected() && Gluten.isSelected() && 
                CookEasy.isSelected()){
  
         jTextAreaINGRED.setText("Olive oil\n 3 cups kale, chopped\n 4 eggs\n"
                 + "2 cups mushrooms, sliced\n 1 onion, chopped\n "
                 + "3 cups cooked sweet potatoes, diced\n 1 pound cooked bacon\n"
                 + " 1/2 cup shredded cheddar cheese");
         jTextAreaINSTRUCT.setText("1. To prepare the filling, heat large skillet "
                 + "and add a small amount of olive oil.\n"
                 + "2. Once hot, sauté onions, garlic and mushrooms until tender.\n"
                 + "3.Add in kale and sweet potato and continue cooking until all "
                 + "vegetables are tender and begin to brown.\n"
                 + "4.Remove vegetables from heat and place them in a medium bowl.\n"
                 + "5.In same skillet, scramble the eggs. Once cooked, add to the "
                 + "bowl with the vegetables.\n"
                 + "6.Mix in shredded cheese and cooked bacon.\n"
                 + "7.To make, place tortilla on a work surface and divide the egg,"
                 + "vegetable and bacon filling among the wraps.\n"
                 + "8.Fold in the ends and roll up the burritos tightly.\n");
         
         NameOfDish.setText("Sweet Potato and Kale Breakfast Wrap");
     
        }
        if ( Bfast.isSelected() && Veggie.isSelected() || Pesc.isSelected() && 
                Gluten.isSelected() && CookEasy.isSelected()){
            jTextAreaINGRED.setText("1 slice gluten free whole grain bread, toasted\n"
                 + "1 oz mashed (1/4 small hass) avocado\n cooking spray\n "
                 + "1 large egg\n kosher salt and black pepper \n ");
         jTextAreaINSTRUCT.setText("1.Mash the avocado in a small bowl and season "
                 + "with salt and pepper.\n"
                 + "2.Heat a small nonstick skillet over low heat, spray with oil"
                 + " and gently crack the egg into the skillet.\n"
                 + "3.Cover and cook to your liking.\n"
                 + "4.Place mashed avocado over toast, top with egg, salt and pepper "
                 + "and hot sauce if desired!\n");
         
         NameOfDish.setText("Avocado and Egg Toast");
        }
        if ( Bfast.isSelected() && Vegan.isSelected() && Gluten.isSelected() && 
                CookEasy.isSelected()){
            jTextAreaINGRED.setText("1/4 cup chocolate oats\n"
                 + "1 tbsp peanut butter (melted)\n 1/2 banana\n "
                 + "1–2 tbsp dark Chocolate chips\n dash of sea salt\n 1–2 tbsp chopped nuts");
         jTextAreaINSTRUCT.setText("1. For cooked gluten free oatmeal, stir in "
                 + "Chocolate Chips or cocoa after cooked.\n"
                 + "2. Heat each Udis Gluten Free tortilla wrap in the microwave "
                 + "for 10 -15 seconds so they can fold easily.\n"
                 + "3. Warm the nut butters so they melt and spread evenly on tortillas.\n"
                 + "4.Then fill each tortilla with ingredients.\n"
                 + "5.Fold each tortilla at the bottom, roll up.\n"
                 + "6.Place each tortilla in a large square foil piece of paper.\n"
                 + "7.Roll tightly folding at the ends.");
         
          NameOfDish.setText("Chunky Monkey Oatmeal Breakfast Wrap");
            
            
        }
        //Lunch
        if ( Lunch.isSelected() && Vegan.isSelected() && Nuts.isSelected() && 
                CookEasy.isSelected()){
            jTextAreaINGRED.setText("1 large, ripe avocado\n Juice of 1 lime\n"
                 + "1 15-oz. can chickpeas\n Bread of your choice\n "
                 + "2 Tbsp. chopped green onions\n 1/4 cup chopped fresh cilantro\n"
                    + "Sandwich toppings (Lettuce and Tomatoes)\n Salt and pepper");
         jTextAreaINSTRUCT.setText("1. In a medium bowl, smash the chickpeas and"
                 + " avocado together using a fork or large spoon.\n"
                 + "2. Add in the cilantro, green onions, and lime juice and stir.\n"
                 + "3. Season with salt and pepper.\n"
                 + "4.Spread onto bread and top with your favorite sandwich toppings.\n");
         
         NameOfDish.setText("Smashed Chickpea and Avocado Salad Sandwich");
         
            
        } 
        if ( Lunch.isSelected() && Veggie.isSelected() && NA.isSelected() && 
                CookMed.isSelected()){
             jTextAreaINGRED.setText("6 ounces (2 cups) whole grain fusilli or rotini pasta\n"
                     + "⅓ cup extra-virgin olive oil\n ½ teaspoon fine sea salt\n"
                     + "2 pints cherry or grape tomatoes\n "
                     + "8 ounces mozzarella “pearls”, or one mozzarella ball, torn into bite-sized pieces\n"
                     + " Several sprigs of fresh basil (enough for 2+ tablespoons chopped)\n"
                     + "2 to 3 teaspoons white balsamic vinegar or regular balsamic vinegar, to taste");
            jTextAreaINSTRUCT.setText("1.Bring a large pot of salted water to boil and cook the pasta.\n"
                    + "2.Drain the pasta and set it aside.\n"
                    + "3.Combine the olive oil, tomatoes and salt in a large, non-reactive skillet(medium heat).\n"
                    + "4. Cook, stirring occasionally, until most of the tomatoes have started "
                    + "to burst out of their skins and the olive oil has a light red hue (about 6 to 12 minutes).\n"
                    + "5.Remove the skillet from the heat and stir in the cooked pasta.\n"
                    + "6.Stir the mozzarella balls and basil into the pasta.\n");
            
            NameOfDish.setText("Caprese Pasta Salad");
            
        } 
        if ( Lunch.isSelected() && Pesc.isSelected() && NA.isSelected() && 
                CookMed.isSelected()){
            jTextAreaINGRED.setText("4 tablespoons unsalted butter\n lemon wedges\n"
                    + "salt and pepper\n 1 tablespoon drained capers\n"
                    + "1 pint cherry or grape tomatoes\n"
                    + "4 thick salmon fillets or steaks (about 1 1/2 pounds total), skin on");
            jTextAreaINSTRUCT.setText("1.Heat the oven to 475°F. \n"
                    + "Put the butter and a sprinkle of salt and pepper in a large skillet over medium-high heat.\n"
                    + "When the foam subsides, add the salmon and sprinkle with salt and pepper.\n"
                    + "2. Cook, undisturbed, until the salmon sizzles and the butter darkens, 2 to 3 minutes.\n"
                    + "Scatter the tomatoes and capers around the fish and transfer the pan to the oven.\n"
                    + "3.Roast without turning until the salmon browns on top and the inside is as cooked as you like.\n"
                    + "4. Serve the salmon steaks with the tomato-caper sauce spooned on top, passing the lemon wedges at the table.");
            
                NameOfDish.setText("Brown-Butter Salmon With Tomatoes And Capers");
        }
        if ( Lunch.isSelected() && EatAll.isSelected() && Dairy.isSelected() && 
                CookHard.isSelected()){
            
        }
        //Dinner
        if(Din.isSelected() && EatAll.isSelected() && Gluten.isSelected() && Egg.isSelected()&&
                Dairy.isSelected() && Nuts.isSelected() && CookMed.isSelected()){
            jTextAreaINGRED.setText("1 bunch fresh parsley\n 1 bunch fresh cilantro\n"
                    + "1 to 2 cloves garlic\n 1 large red onion, halved and sliced\n"
                    + "2 tablespoons red wine vinegar\n 3 tablespoons lemon juice\n"
                    + "Kosher salt and freshly ground pepper\n 1/4 cup lager beer\n"
                    + "1/2 cup plus 1 tablespoon extra-virgin olive oil\n"
                    + "1 pound chuck or top round steak (London broil)\n"
                    + "3 poblano peppers, seeded and cut into strips\n 8 8-inch flour tortillas.");
            jTextAreaINSTRUCT.setText("1.Combine the parsley and cilantro, garlic, "
                    + "half of the sliced onion, 1 tablespoon salt, 1 teaspoon pepper, vinegar, "
                    + "2 tablespoons lemon juice and 1/2 cup olive oil in a food processor.\n"
                    + "2.Blend into a thick and smooth chimichurri sauce.\n"
                    + "3.Pierce both sides of the steak with a fork several times.\n"
                    + " Place in a resealable plastic bag and add half of the sauce.\n"
                    + "Seal the bag and turn to coat the steak; refrigerate for at least 1 hour.\n"
                    + "4.Preheat a grill to medium-high. Remove the steak from the bag.\n"
                    + "Season with salt and pepper and grill until medium-rare, about 6 minutes per side.\n"
                    + "Let rest, loosely covered with foil, for 10 minutes.\n"
                    + "5.Meanwhile, heat the remaining 1 tablespoon olive oil in a large skillet over medium-high heat. \n"
                    + "Add the peppers and the remaining sliced onion half.\n"
                    + "6.Saute until the vegetables are softened and caramelized around the edges, about 8 minutes.\n"
                    + "Add the beer, cover and cook until the peppers are tender, about 5 minutes.\n"
                    + "7.Warm the tortillas on the grill. Thinly slice the steak on the bias.\n"
                    + "8.Drizzle chimichurri sauce  over the fajitas.");
                            
            
            
            NameOfDish.setText("Steak Fajitas with Chimichurri and Drunken Peppers");
        }
        //Snack
        
        //Dessert
        if ( Dessert.isSelected() && Vegan.isSelected() && Gluten.isSelected() && 
                CookMed.isSelected()){
            
        }
        
     
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonGoActionPerformed

    private void NutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NutsActionPerformed

    private void EggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EggActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EggActionPerformed

    private void PescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PescActionPerformed

    
    private void EatAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EatAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EatAllActionPerformed

    private void LunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LunchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LunchActionPerformed

    private void BfastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BfastActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void StartOver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartOver1ActionPerformed
        // TODO add your handling code here:
        buttonGroupMeal.clearSelection();
        buttonGroupLifestyle.clearSelection();
        buttonGroupTime.clearSelection();
        Gluten.setSelected(false);
        Egg.setSelected(false);
        Dairy.setSelected(false);
        Nuts.setSelected(false);
        NA.setSelected(false);
        jTextAreaINGRED.setText("  ");
        jTextAreaINSTRUCT.setText(" ");
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_StartOver1ActionPerformed

    private void NextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton1ActionPerformed
        // TODO add your handling code here:
        Title.setText(jTextFieldName.getText()+ "'s CookBook");
        
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_NextButton1ActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void BackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_BackButton2ActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        
        buttonGroupMeal.clearSelection();
        buttonGroupLifestyle.clearSelection();
        buttonGroupTime.clearSelection();
        Gluten.setSelected(false);
        Egg.setSelected(false);
        Dairy.setSelected(false);
        Nuts.setSelected(false);
        NA.setSelected(false);
        jTextAreaINGRED.setText("  ");
        jTextAreaINSTRUCT.setText(" ");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void StartOver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartOver1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StartOver1MouseClicked

    private void NameOfDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameOfDishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameOfDishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cookbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cookbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cookbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cookbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cookbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BackButton2;
    private javax.swing.JRadioButton Bfast;
    private javax.swing.JButton ClearButton;
    private javax.swing.JRadioButton CookEasy;
    private javax.swing.JRadioButton CookHard;
    private javax.swing.JRadioButton CookMed;
    private javax.swing.JCheckBox Dairy;
    private javax.swing.JRadioButton Dessert;
    private javax.swing.JRadioButton Din;
    private javax.swing.JRadioButton EatAll;
    private javax.swing.JCheckBox Egg;
    private javax.swing.JCheckBox Gluten;
    private javax.swing.JLabel HungryQ;
    private javax.swing.JLabel Ingredients;
    private javax.swing.JLabel Instructions;
    private javax.swing.JLabel LifestyleQ;
    private javax.swing.JRadioButton Lunch;
    private javax.swing.JCheckBox NA;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameOfDish;
    private javax.swing.JButton NextButton1;
    private javax.swing.JCheckBox Nuts;
    private javax.swing.JRadioButton Pesc;
    private javax.swing.JRadioButton Snack;
    private javax.swing.JButton StartOver1;
    private javax.swing.JLabel Title;
    private javax.swing.JRadioButton Vegan;
    private javax.swing.JRadioButton Veggie;
    private javax.swing.ButtonGroup buttonGroupLifestyle;
    private javax.swing.ButtonGroup buttonGroupMeal;
    private javax.swing.ButtonGroup buttonGroupTime;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextAreaINGRED;
    private javax.swing.JTextArea jTextAreaINSTRUCT;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
